name: cpp_nuget_pack
description: "A new Flutter project."
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  file_selector: ^1.0.0
  flutter_svg: ^2.0.0
  fluent_ui: ^4.15.1
  catppuccin_flutter: ^1.0.0
  yaml: ^3.1.4
  yaml_edit: ^2.2.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/catppuccin/latte/
    - assets/icons/catppuccin/mocha/
  fonts:
    - family: HarmonyOS_Sans_SC
      fonts:
        - asset: assets/fonts/HarmonyOS_Sans_SC_Regular.ttf
